qsub -q bigq -N CutOp5 -wd ~/logfiles/ cutop_script/cutop_MuMuE_5.sh
qsub -q bigq -N CutOp10 -wd ~/logfiles/ cutop_script/cutop_MuMuE_10.sh
qsub -q bigq -N CutOp20 -wd ~/logfiles/ cutop_script/cutop_MuMuE_20.sh
qsub -q bigq -N CutOp30 -wd ~/logfiles/ cutop_script/cutop_MuMuE_30.sh
qsub -q bigq -N CutOp40 -wd ~/logfiles/ cutop_script/cutop_MuMuE_40.sh
qsub -q bigq -N CutOp50 -wd ~/logfiles/ cutop_script/cutop_MuMuE_50.sh
qsub -q bigq -N CutOp60 -wd ~/logfiles/ cutop_script/cutop_MuMuE_60.sh
qsub -q bigq -N CutOp70 -wd ~/logfiles/ cutop_script/cutop_MuMuE_70.sh
qsub -q bigq -N CutOp90 -wd ~/logfiles/ cutop_script/cutop_MuMuE_90.sh
qsub -q bigq -N CutOp100 -wd ~/logfiles/ cutop_script/cutop_MuMuE_100.sh
qsub -q bigq -N CutOp150 -wd ~/logfiles/ cutop_script/cutop_MuMuE_150.sh
qsub -q bigq -N CutOp200 -wd ~/logfiles/ cutop_script/cutop_MuMuE_200.sh
qsub -q bigq -N CutOp300 -wd ~/logfiles/ cutop_script/cutop_MuMuE_300.sh
qsub -q bigq -N CutOp400 -wd ~/logfiles/ cutop_script/cutop_MuMuE_400.sh
qsub -q bigq -N CutOp500 -wd ~/logfiles/ cutop_script/cutop_MuMuE_500.sh
qsub -q bigq -N CutOp700 -wd ~/logfiles/ cutop_script/cutop_MuMuE_700.sh
qsub -q bigq -N CutOp1000 -wd ~/logfiles/ cutop_script/cutop_MuMuE_1000.sh
